### ISSUE TITLE
Add CurseForge App compatibility

### ISSUE THREAD

**Issue by Keralin** [fang2hou/WeakAurasPatched#1]
Hi there!

Is there any possibility of adding this project to curseforge app? [CurseForge](https://www.curseforge.com/wow) 
It's like the repository for the addons for users that are using the [CurseForge App](https://www.curseforge.com/download/app). This will help us to auto-update the addon (like wowup) instead of doing it manually. 

Thank for your time!

**Comment by fang2hou** [comment]
Actually, I tried, and Curse said that even though the license is accepted for redistribution, they want to respect the decision of the WeakAuras Team, so publishing on Curse is not currently possible.

**Comment by Keralin** [comment]
> Actually, I tried, and Curse said that even though the license is accepted for redistribution, they want to respect the decision of the WeakAuras Team, so publishing on Curse is not currently possible.

What a pity. Anyways thanks for your time 😄
